const data = [
  {
    id: 'MLB1607748387',
    site_id: 'MLB',
    title: 'Pc Computador Cpu Intel Core I5 + Ssd 240gb, 8gb Memória Ram',
    seller: {
      id: 459757635,
      permalink: 'http://perfil.mercadolivre.com.br/TECH.POWER+SHOP',
      registration_date: '2019-08-09T14:58:41.000-04:00',
      car_dealer: false,
      real_estate_agency: false,
      tags: [
        'normal',
        'credits_profile',
        'messages_as_seller',
      ],
      seller_reputation: {
        power_seller_status: 'platinum',
        level_id: '5_green',
        metrics: {
          cancellations: {
            period: '60 days',
            rate: 0.0036,
            value: 12,
          },
          claims: {
            period: '60 days',
            rate: 0.0191,
            value: 62,
          },
          delayed_handling_time: {
            period: '60 days',
            rate: 0.1349,
            value: 424,
          },
          sales: {
            period: '60 days',
            completed: 3087,
          },
        },
        transactions: {
          canceled: 1348,
          period: 'historic',
          total: 22050,
          ratings: {
            negative: 0.02,
            neutral: 0.02,
            positive: 0.96,
          },
          completed: 20702,
        },
      },
    },
    price: 1592.09,
    prices: {
      id: 'MLB1607748387',
      prices: [
        {
          id: '183',
          type: 'standard',
          amount: 1829.99,
          regular_amount: null,
          currency_id: 'BRL',
          last_updated: '2022-01-04T18:04:25Z',
          conditions: {
            context_restrictions: [
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          exchange_rate_context: 'DEFAULT',
          metadata: {
          },
        },
        {
          id: '288',
          type: 'promotion',
          amount: 1592.09,
          regular_amount: 1829.99,
          currency_id: 'BRL',
          last_updated: '2022-03-25T10:57:21Z',
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: '2022-03-25T03:00:00Z',
            end_time: '2022-04-01T02:59:59Z',
            eligible: true,
          },
          exchange_rate_context: 'DEFAULT',
          metadata: {
            promotion_id: '35533873-MLB1607748387',
            promotion_type: 'custom',
          },
        },
      ],
      presentation: {
        display_currency: 'BRL',
      },
      payment_method_prices: [
        {
          id: '95a94c97-3149-4f5d-b292-7a25864a573b',
          conditions: {
            allowed_methods: [
              {
                id: 'pix',
                issuer_id: null,
                payment_type_id: 'bank_transfer',
                installments: null,
              },
            ],
            start_time: '2022-01-16T03:00:00Z',
            end_time: '2022-01-20T02:00:00Z',
            restricted_to_prices: [
            ],
          },
          value: 5,
          type: 'percentage',
          currency_id: null,
          metadata: {
            purchase_discount_id: 'MLB510001',
            purchase_discount_type: 'BD',
            purchase_discount_campaign_id: 'P-MLB3826001',
            purchase_discount_rebate_id: 'MLB1607748387-98adadc1-6b73-4225-a5d3-4e690c6ee748',
          },
          exchange_rate_context: 'DEFAULT',
        },
      ],
      reference_prices: [
        {
          id: '289',
          type: 'min_standard',
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          amount: 1829.99,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          tags: [
          ],
          last_updated: '2022-03-26T04:30:59Z',
        },
        {
          id: '290',
          type: 'was',
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: '2022-03-26T04:30:58Z',
            end_time: '2022-04-02T04:30:58Z',
            eligible: true,
          },
          amount: 1610.39,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          tags: [
          ],
          last_updated: '2022-03-26T04:30:59Z',
        },
      ],
      purchase_discounts: [
        {
          purchase_discount_id: 'MLB510001',
          campaign_id: 'P-MLB3826001',
          rebate_id: 'MLB1607748387-98adadc1-6b73-4225-a5d3-4e690c6ee748',
          type: 'BD',
          discount_percentage: 0.05,
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: '2022-01-16T03:00:00Z',
            end_time: '2022-01-20T02:00:00Z',
            eligible: true,
          },
          purchase_min_amount: 0,
          max_discount_amount: 300000,
          max_benefit_count: 1,
        },
      ],
    },
    sale_price: null,
    currency_id: 'BRL',
    available_quantity: 500,
    sold_quantity: 5000,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_pro',
    stop_time: '2041-10-16T10:04:35.000Z',
    condition: 'new',
    permalink: 'https://produto.mercadolivre.com.br/MLB-1607748387-pc-computador-cpu-intel-core-i5-ssd-240gb-8gb-memoria-ram-_JM',
    thumbnail: 'http://http2.mlstatic.com/D_600798-MLB49337902152_032022-I.jpg',
    thumbnail_id: '600798-MLB49337902152_032022',
    accepts_mercadopago: true,
    installments: {
      quantity: 12,
      amount: 132.67,
      rate: 0,
      currency_id: 'BRL',
    },
    address: {
      state_id: 'BR-SP',
      state_name: 'São Paulo',
      city_id: 'BR-SP-28',
      city_name: 'São José do Rio Preto',
    },
    shipping: {
      free_shipping: true,
      mode: 'me2',
      tags: [
        'mandatory_free_shipping',
      ],
      logistic_type: 'cross_docking',
      store_pick_up: false,
    },
    seller_address: {
      id: '',
      comment: '',
      address_line: '',
      zip_code: '',
      country: {
        id: 'BR',
        name: 'Brasil',
      },
      state: {
        id: 'BR-SP',
        name: 'São Paulo',
      },
      city: {
        id: 'BR-SP-28',
        name: 'São José do Rio Preto',
      },
      latitude: '',
      longitude: '',
    },
    attributes: [
      {
        id: 'BRAND',
        name: 'Marca',
        value_name: 'Tech Power',
        value_struct: null,
        values: [
          {
            id: null,
            name: 'Tech Power',
            struct: null,
            source: 3376461333454861,
          },
        ],
        attribute_group_id: 'OTHERS',
        value_id: null,
        attribute_group_name: 'Outros',
        source: 3376461333454861,
      },
      {
        value_id: '2230284',
        value_struct: null,
        attribute_group_id: 'OTHERS',
        id: 'ITEM_CONDITION',
        name: 'Condição do item',
        value_name: 'Novo',
        values: [
          {
            struct: null,
            source: 2860837171021627,
            id: '2230284',
            name: 'Novo',
          },
        ],
        attribute_group_name: 'Outros',
        source: 2860837171021627,
      },
      {
        id: 'MODEL',
        name: 'Modelo',
        value_name: 'Desktop',
        value_struct: null,
        value_id: null,
        values: [
          {
            id: null,
            name: 'Desktop',
            struct: null,
            source: 2860837171021627,
          },
        ],
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        source: 2860837171021627,
      },
    ],
    differential_pricing: {
      id: 33580182,
    },
    original_price: 1829.99,
    category_id: 'MLB1649',
    official_store_id: null,
    domain_id: 'MLB-DESKTOP_COMPUTERS',
    catalog_product_id: null,
    tags: [
      'brand_verified',
      'good_quality_picture',
      'good_quality_thumbnail',
      'loyalty_discount_eligible',
      'immediate_payment',
      'cart_eligible',
      'shipping_guaranteed',
      'best_seller_candidate',
    ],
    order_backend: 1,
    use_thumbnail_id: true,
    offer_score: null,
    offer_share: null,
    match_score: null,
    winner_item_id: null,
    melicoin: null,
    discounts: null,
  },
  {
    id: 'MLB1930876153',
    site_id: 'MLB',
    title: 'Notebook Multilaser Legacy Book Pc310 Preta 14.1 , Intel Celeron N3000 4gb De Ram 64gb Ssd, Intel Hd Graphics 1366x768px Windows 10 Home',
    seller: {
      id: 564615359,
      permalink: 'http://perfil.mercadolivre.com.br/V.I.K_',
      registration_date: '2020-05-07T10:24:44.000-04:00',
      car_dealer: false,
      real_estate_agency: false,
      tags: [
        'brand',
        'eshop',
        'mshops',
        'large_seller',
        'credits_profile',
        'messages_as_seller',
      ],
      eshop: {
        seller: 564615359,
        eshop_rubro: null,
        eshop_id: 422472,
        nick_name: 'V.I.K_',
        site_id: 'MLB',
        eshop_logo_url: 'http://resources.mlstatic.com/eshops/564615359v5a57d1.png',
        eshop_status_id: 1,
        eshop_experience: 0,
        eshop_locations: [
        ],
      },
      seller_reputation: {
        power_seller_status: 'platinum',
        level_id: '5_green',
        metrics: {
          cancellations: {
            period: '60 days',
            rate: 0,
            value: 0,
          },
          claims: {
            period: '60 days',
            rate: 0.0083,
            value: 471,
          },
          delayed_handling_time: {
            period: '60 days',
            rate: 0.0026,
            value: 145,
          },
          sales: {
            period: '60 days',
            completed: 53106,
          },
        },
        transactions: {
          canceled: 16386,
          period: 'historic',
          total: 267446,
          ratings: {
            negative: 0.04,
            neutral: 0.01,
            positive: 0.95,
          },
          completed: 251060,
        },
      },
    },
    price: 1399,
    prices: {
      id: 'MLB1930876153',
      prices: [
        {
          id: '99',
          type: 'standard',
          amount: 1999,
          regular_amount: null,
          currency_id: 'BRL',
          last_updated: '2022-03-15T19:39:07Z',
          conditions: {
            context_restrictions: [
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          exchange_rate_context: 'DEFAULT',
          metadata: {
          },
        },
        {
          id: '122',
          type: 'promotion',
          amount: 1399,
          regular_amount: 1999,
          currency_id: 'BRL',
          last_updated: '2022-03-23T12:55:54Z',
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: '2022-02-28T02:30:00Z',
            end_time: '2022-04-01T02:59:00Z',
            eligible: true,
          },
          exchange_rate_context: 'DEFAULT',
          metadata: {
            campaign_id: 'MLB7655',
            promotion_id: 'MLB7655',
            promotion_type: 'campaign',
          },
        },
      ],
      presentation: {
        display_currency: 'BRL',
      },
      payment_method_prices: [
      ],
      reference_prices: [
        {
          id: '123',
          type: 'min_standard',
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          amount: 1299,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          tags: [
          ],
          last_updated: '2022-03-29T04:28:51Z',
        },
        {
          id: '124',
          type: 'was',
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: '2022-03-29T04:28:50Z',
            end_time: '2022-04-05T04:28:50Z',
            eligible: true,
          },
          amount: 1249,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          tags: [
          ],
          last_updated: '2022-03-29T04:28:51Z',
        },
      ],
      purchase_discounts: [
      ],
    },
    sale_price: null,
    currency_id: 'BRL',
    available_quantity: 430,
    sold_quantity: 717,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_pro',
    stop_time: '2042-03-10T19:38:06.000Z',
    condition: 'new',
    permalink: 'https://www.mercadolivre.com.br/notebook-multilaser-legacy-book-pc310-preta-141-intel-celeron-n3000-4gb-de-ram-64gb-ssd-intel-hd-graphics-1366x768px-windows-10-home/p/MLB16263913',
    thumbnail: 'http://http2.mlstatic.com/D_892016-MLA44927459054_022021-I.jpg',
    thumbnail_id: '892016-MLA44927459054_022021',
    accepts_mercadopago: true,
    installments: {
      quantity: 12,
      amount: 116.58,
      rate: 0,
      currency_id: 'BRL',
    },
    address: {
      state_id: 'BR-SP',
      state_name: 'São Paulo',
      city_id: 'BR-SP-44',
      city_name: 'São Paulo',
    },
    shipping: {
      free_shipping: true,
      mode: 'me2',
      tags: [
        'fulfillment',
        'self_service_out',
        'mandatory_free_shipping',
      ],
      logistic_type: 'fulfillment',
      store_pick_up: false,
    },
    seller_address: {
      id: '',
      comment: '',
      address_line: '',
      zip_code: '',
      country: {
        id: 'BR',
        name: 'Brasil',
      },
      state: {
        id: 'BR-SP',
        name: 'São Paulo',
      },
      city: {
        id: 'BR-SP-44',
        name: 'São Paulo',
      },
      latitude: '',
      longitude: '',
    },
    attributes: [
      {
        source: 1,
        name: 'Marca',
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        value_struct: null,
        values: [
          {
            id: '31163',
            name: 'Multilaser',
            struct: null,
            source: 1,
          },
        ],
        id: 'BRAND',
        value_id: '31163',
        value_name: 'Multilaser',
      },
      {
        value_id: '2230284',
        value_name: 'Novo',
        value_struct: null,
        values: [
          {
            id: '2230284',
            name: 'Novo',
            struct: null,
            source: 6808261514773724,
          },
        ],
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        id: 'ITEM_CONDITION',
        name: 'Condição do item',
        source: 6808261514773724,
      },
      {
        value_struct: null,
        source: 1,
        id: 'LINE',
        name: 'Linha',
        value_id: '7963805',
        attribute_group_name: 'Outros',
        value_name: 'Legacy Book',
        values: [
          {
            struct: null,
            source: 1,
            id: '7963805',
            name: 'Legacy Book',
          },
        ],
        attribute_group_id: 'OTHERS',
      },
      {
        value_id: '9232563',
        values: [
          {
            id: '9232563',
            name: 'PC310',
            struct: null,
            source: 1,
          },
        ],
        source: 1,
        name: 'Modelo',
        value_name: 'PC310',
        value_struct: null,
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        id: 'MODEL',
      },
      {
        source: 1,
        id: 'PROCESSOR_BRAND',
        name: 'Marca do processador',
        value_id: '7855833',
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        value_name: 'Intel',
        value_struct: null,
        values: [
          {
            id: '7855833',
            name: 'Intel',
            struct: null,
            source: 1,
          },
        ],
      },
      {
        id: 'PROCESSOR_LINE',
        value_struct: null,
        attribute_group_name: 'Outros',
        name: 'Linha do processador',
        value_id: '44273',
        value_name: 'Celeron',
        values: [
          {
            id: '44273',
            name: 'Celeron',
            struct: null,
            source: 1,
          },
        ],
        attribute_group_id: 'OTHERS',
        source: 1,
      },
      {
        attribute_group_id: 'OTHERS',
        id: 'PROCESSOR_MODEL',
        values: [
          {
            source: 1,
            id: '76008',
            name: 'N3000',
            struct: null,
          },
        ],
        value_name: 'N3000',
        value_struct: null,
        attribute_group_name: 'Outros',
        source: 1,
        name: 'Modelo do processador',
        value_id: '76008',
      },
    ],
    differential_pricing: {
      id: 33580182,
    },
    original_price: 1999,
    category_id: 'MLB1652',
    official_store_id: 2972,
    domain_id: 'MLB-NOTEBOOKS',
    catalog_product_id: 'MLB16263913',
    tags: [
      'loyalty_discount_eligible',
      'extended_warranty_eligible',
      'good_quality_picture',
      'good_quality_thumbnail',
      'immediate_payment',
      'cart_eligible',
      'shipping_guaranteed',
      'best_seller_candidate',
    ],
    catalog_listing: true,
    use_thumbnail_id: true,
    offer_score: null,
    offer_share: null,
    match_score: null,
    winner_item_id: null,
    melicoin: null,
    discounts: null,
    order_backend: 2,
  },
];

export default data;
