const data = [
  {
    id: 'MLB1985412718',
    site_id: 'MLB',
    title: 'Acessório Carro Apoio Braço Encosto Descanso Porta Objetos',
    seller: {
      id: 567635787,
      permalink: 'http://perfil.mercadolivre.com.br/MULTIPLAPART',
      registration_date: '2020-10-16T12:14:27.000-04:00',
      car_dealer: false,
      real_estate_agency: false,
      tags: [
        'normal',
        'credits_profile',
        'messages_as_seller',
      ],
      seller_reputation: {
        power_seller_status: 'platinum',
        level_id: '5_green',
        metrics: {
          cancellations: {
            period: '60 days',
            rate: 0.0018,
            value: 7,
          },
          claims: {
            period: '60 days',
            rate: 0.011,
            value: 41,
          },
          delayed_handling_time: {
            period: '60 days',
            rate: 0.0068,
            value: 24,
          },
          sales: {
            period: '60 days',
            completed: 3421,
          },
        },
        transactions: {
          canceled: 918,
          period: 'historic',
          total: 12330,
          ratings: {
            negative: 0.03,
            neutral: 0.01,
            positive: 0.96,
          },
          completed: 11412,
        },
      },
    },
    price: 144.9,
    prices: {
      id: 'MLB1985412718',
      prices: [
        {
          id: '1',
          type: 'standard',
          amount: 144.9,
          regular_amount: null,
          currency_id: 'BRL',
          last_updated: '2021-08-19T13:50:40Z',
          conditions: {
            context_restrictions: [
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          exchange_rate_context: 'DEFAULT',
          metadata: {
          },
        },
      ],
      presentation: {
        display_currency: 'BRL',
      },
      payment_method_prices: [
        {
          id: 'e55291d6-dbb1-4822-b8e2-e76aec8c901f',
          conditions: {
            allowed_methods: [
              {
                id: 'consumer_credits',
                issuer_id: 12364,
                payment_type_id: 'digital_currency',
                installments: null,
              },
            ],
            start_time: '2022-02-21T03:00:00Z',
            end_time: '2022-02-25T02:00:00Z',
            restricted_to_prices: [
            ],
          },
          value: 10,
          type: 'percentage',
          currency_id: null,
          metadata: {
            purchase_discount_id: 'MLB587001',
            purchase_discount_type: 'BD',
            purchase_discount_campaign_id: 'P-MLB4508001',
            purchase_discount_rebate_id: 'MLB1985412718-757e6a31-a42b-4688-b8cd-c2fd73f7e3fe',
          },
          exchange_rate_context: 'DEFAULT',
        },
      ],
      reference_prices: [
        {
          id: '82',
          type: 'min_standard',
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          amount: 144.9,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          tags: [
          ],
          last_updated: '2022-03-02T21:57:39Z',
        },
      ],
      purchase_discounts: [
        {
          purchase_discount_id: 'MLB587001',
          campaign_id: 'P-MLB4508001',
          rebate_id: 'MLB1985412718-757e6a31-a42b-4688-b8cd-c2fd73f7e3fe',
          type: 'BD',
          discount_percentage: 0.1,
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: '2022-02-21T03:00:00Z',
            end_time: '2022-02-25T02:00:00Z',
            eligible: true,
          },
          purchase_min_amount: 0,
          max_discount_amount: 70,
          max_benefit_count: 1,
          funding_mode: 'coupon',
        },
      ],
    },
    sale_price: null,
    currency_id: 'BRL',
    available_quantity: 5000,
    sold_quantity: 500,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_pro',
    stop_time: '2041-08-14T04:00:00.000Z',
    condition: 'new',
    permalink: 'https://produto.mercadolivre.com.br/MLB-1985412718-acessorio-carro-apoio-braco-encosto-descanso-porta-objetos-_JM',
    thumbnail: 'http://http2.mlstatic.com/D_713380-MLB49213845076_022022-I.jpg',
    thumbnail_id: '713380-MLB49213845076_022022',
    accepts_mercadopago: true,
    installments: {
      quantity: 6,
      amount: 24.15,
      rate: 0,
      currency_id: 'BRL',
    },
    address: {
      state_id: 'BR-MG',
      state_name: 'Minas Gerais',
      city_id: 'TUxCQ0JFTGU0ODdm',
      city_name: 'Belo Horizonte',
    },
    shipping: {
      free_shipping: true,
      mode: 'me2',
      tags: [
        'mandatory_free_shipping',
      ],
      logistic_type: 'cross_docking',
      store_pick_up: false,
    },
    seller_address: {
      id: '',
      comment: '',
      address_line: '',
      zip_code: '',
      country: {
        id: 'BR',
        name: 'Brasil',
      },
      state: {
        id: 'BR-MG',
        name: 'Minas Gerais',
      },
      city: {
        id: 'TUxCQ0JFTGU0ODdm',
        name: 'Belo Horizonte',
      },
      latitude: '',
      longitude: '',
    },
    attributes: [
      {
        value_id: null,
        values: [
          {
            id: null,
            name: 'Artefactum',
            struct: null,
            source: 2860837171021627,
          },
        ],
        source: 2860837171021627,
        id: 'BRAND',
        value_name: 'Artefactum',
        value_struct: null,
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        name: 'Marca',
      },
      {
        value_id: '2230284',
        value_name: 'Novo',
        value_struct: null,
        attribute_group_id: 'OTHERS',
        source: 2860837171021627,
        name: 'Condição do item',
        values: [
          {
            id: '2230284',
            name: 'Novo',
            struct: null,
            source: 2860837171021627,
          },
        ],
        attribute_group_name: 'Outros',
        id: 'ITEM_CONDITION',
      },
      {
        value_id: null,
        value_name: '27 cm',
        values: [
          {
            id: null,
            name: '27 cm',
            struct: {
              number: 27,
              unit: 'cm',
            },
            source: 2860837171021627,
          },
        ],
        attribute_group_name: 'Outros',
        source: 2860837171021627,
        id: 'LENGTH',
        name: 'Comprimento',
        value_struct: {
          number: 27,
          unit: 'cm',
        },
        attribute_group_id: 'OTHERS',
      },
    ],
    differential_pricing: {
      id: 35713362,
    },
    original_price: null,
    category_id: 'MLB31156',
    official_store_id: null,
    domain_id: 'MLB-AUTOMOTIVE_ARMRESTS',
    catalog_product_id: null,
    tags: [
      'loyalty_discount_eligible',
      'good_quality_picture',
      'good_quality_thumbnail',
      'immediate_payment',
      'cart_eligible',
      'best_seller_candidate',
    ],
    order_backend: 1,
    use_thumbnail_id: true,
    offer_score: null,
    offer_share: null,
    match_score: null,
    winner_item_id: null,
    melicoin: null,
    discounts: null,
  },
  {
    id: 'MLB2096085553',
    site_id: 'MLB',
    title: 'Cadeira Infantil Para Carro Fisher-price All-stages Fix 2.0 Cinza',
    seller: {
      id: 400734623,
      permalink: 'http://perfil.mercadolivre.com.br/LOULI+BABY',
      registration_date: '2019-02-04T10:17:29.000-04:00',
      car_dealer: false,
      real_estate_agency: false,
      tags: [
        'normal',
        'eshop',
        'mshops',
        'credits_profile',
        'messages_as_seller',
      ],
      eshop: {
        seller: 400734623,
        eshop_rubro: null,
        eshop_id: 488023,
        nick_name: 'LOULI BABY',
        site_id: 'MLB',
        eshop_logo_url: 'http://resources.mlstatic.com/eshops/400734623v0beba1.png',
        eshop_status_id: 1,
        eshop_experience: 0,
        eshop_locations: [
        ],
      },
      seller_reputation: {
        power_seller_status: 'platinum',
        level_id: '5_green',
        metrics: {
          cancellations: {
            period: '60 days',
            rate: 0,
            value: 2,
          },
          claims: {
            period: '60 days',
            rate: 0.0044,
            value: 7,
          },
          delayed_handling_time: {
            period: '60 days',
            rate: 0,
            value: 0,
          },
          sales: {
            period: '60 days',
            completed: 1495,
          },
        },
        transactions: {
          canceled: 470,
          period: 'historic',
          total: 9544,
          ratings: {
            negative: 0.06,
            neutral: 0.02,
            positive: 0.92,
          },
          completed: 9074,
        },
      },
    },
    price: 982,
    prices: {
      id: 'MLB2096085553',
      prices: [
        {},
      ],
      presentation: {
        display_currency: 'BRL',
      },
      payment_method_prices: [
      ],
      reference_prices: [
        {
          id: '41',
          type: 'min_standard',
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          amount: 944,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          tags: [
          ],
          last_updated: '2022-03-01T08:08:38Z',
        },
      ],
      purchase_discounts: [
      ],
    },
    sale_price: null,
    currency_id: 'BRL',
    available_quantity: 14,
    sold_quantity: 109,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_pro',
    stop_time: '2041-11-19T04:00:00.000Z',
    condition: 'new',
    permalink: 'https://www.mercadolivre.com.br/cadeira-infantil-para-carro-fisher-price-all-stages-fix-20-cinza/p/MLB16029356',
    thumbnail: 'http://http2.mlstatic.com/D_890208-MLA43425526686_092020-I.jpg',
    thumbnail_id: '890208-MLA43425526686_092020',
    accepts_mercadopago: true,
    installments: {
      quantity: 10,
      amount: 98.2,
      rate: 0,
      currency_id: 'BRL',
    },
    address: {
      state_id: 'BR-SP',
      state_name: 'São Paulo',
      city_id: 'BR-SP-31',
      city_name: 'Osasco',
    },
    shipping: {
      free_shipping: true,
      mode: 'me2',
      tags: [
        'self_service_out',
        'mandatory_free_shipping',
      ],
      logistic_type: 'cross_docking',
      store_pick_up: false,
    },
    seller_address: {
      id: '',
      comment: '',
      address_line: '',
      zip_code: '',
      country: {
        id: 'BR',
        name: 'Brasil',
      },
      state: {
        id: 'BR-SP',
        name: 'São Paulo',
      },
      city: {
        id: 'BR-SP-31',
        name: 'Osasco',
      },
      latitude: '',
      longitude: '',
    },
    attributes: [
      {
        value_id: '15256',
        value_name: 'Fisher-Price',
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        id: 'BRAND',
        name: 'Marca',
        value_struct: null,
        values: [
          {
            id: '15256',
            name: 'Fisher-Price',
            struct: null,
            source: 1,
          },
        ],
        source: 1,
      },
      {
        id: 'DETAILED_MODEL',
        name: 'Modelo detalhado',
        value_id: '8896900',
        attribute_group_name: 'Outros',
        value_name: 'BB325',
        value_struct: null,
        values: [
          {
            id: '8896900',
            name: 'BB325',
            struct: null,
            source: 1,
          },
        ],
        attribute_group_id: 'OTHERS',
        source: 1,
      },
      {
        name: 'Condição do item',
        value_id: '2230284',
        value_name: 'Novo',
        value_struct: null,
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        id: 'ITEM_CONDITION',
        source: 3045741222775799,
        values: [
          {
            id: '2230284',
            name: 'Novo',
            struct: null,
            source: 3045741222775799,
          },
        ],
      },
      {
        value_name: 'All-Stages Fix',
        values: [
          {
            id: null,
            name: 'All-Stages Fix',
            struct: null,
            source: 3045741222775799,
          },
        ],
        attribute_group_name: 'Outros',
        source: 3045741222775799,
        id: 'LINE',
        name: 'Linha',
        attribute_group_id: 'OTHERS',
        value_id: null,
        value_struct: null,
      },
      {
        name: 'Modelo',
        value_id: '8896896',
        value_name: 'All-Stages Fix 2.0',
        attribute_group_id: 'OTHERS',
        source: 1,
        id: 'MODEL',
        value_struct: null,
        values: [
          {
            id: '8896896',
            name: 'All-Stages Fix 2.0',
            struct: null,
            source: 1,
          },
        ],
        attribute_group_name: 'Outros',
      },
      {
        name: 'Peso',
        source: 4709228965570453,
        attribute_group_name: 'Outros',
        id: 'WEIGHT',
        value_id: '11734057',
        value_name: '9500 g',
        value_struct: {
          number: 9500,
          unit: 'g',
        },
        values: [
          {
            id: '11734057',
            name: '9500 g',
            struct: {
              unit: 'g',
              number: 9500,
            },
            source: 4709228965570453,
          },
        ],
        attribute_group_id: 'OTHERS',
      },
    ],
    differential_pricing: {
      id: 35713366,
    },
    original_price: null,
    category_id: 'MLB1387',
    official_store_id: null,
    domain_id: 'MLB-BABY_CAR_SEATS',
    catalog_product_id: 'MLB16029356',
    tags: [
      'extended_warranty_eligible',
      'good_quality_picture',
      'good_quality_thumbnail',
      'immediate_payment',
      'cart_eligible',
      'best_seller_candidate',
      'shipping_guaranteed',
    ],
    catalog_listing: true,
    use_thumbnail_id: true,
    offer_score: null,
    offer_share: null,
    match_score: null,
    winner_item_id: null,
    melicoin: null,
    discounts: null,
    order_backend: 2,
  },
  {
    id: 'MLB1903752342',
    site_id: 'MLB',
    title: 'Geladeira Portátil Para Caminhão 31 Litros Resfriar 12/24v',
    seller: {
      id: 742803770,
      permalink: 'http://perfil.mercadolivre.com.br/GLOBPRIME',
      registration_date: '2021-04-13T10:03:29.000-04:00',
      car_dealer: false,
      real_estate_agency: false,
      tags: [
        'normal',
        'credits_profile',
        'mshops',
        'messages_as_seller',
      ],
      seller_reputation: {
        power_seller_status: 'platinum',
        level_id: '5_green',
        metrics: {
          cancellations: {
            period: '60 days',
            rate: 0,
            value: 2,
          },
          claims: {
            period: '60 days',
            rate: 0.0166,
            value: 13,
          },
          delayed_handling_time: {
            period: '60 days',
            rate: 0.0237,
            value: 18,
          },
          sales: {
            period: '60 days',
            completed: 723,
          },
        },
        transactions: {
          canceled: 191,
          period: 'historic',
          total: 2503,
          ratings: {
            negative: 0.03,
            neutral: 0.02,
            positive: 0.95,
          },
          completed: 2312,
        },
      },
    },
    price: 2499,
    prices: {
      id: 'MLB1903752342',
      prices: [
        {
          id: '151',
          type: 'standard',
          amount: 2499,
          regular_amount: null,
          currency_id: 'BRL',
          last_updated: '2022-02-25T11:53:17Z',
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          exchange_rate_context: 'DEFAULT',
          metadata: {
          },
        },
        {
          id: '60',
          type: 'standard',
          amount: 2329,
          regular_amount: null,
          currency_id: 'BRL',
          last_updated: '2021-12-03T12:29:22Z',
          conditions: {
            context_restrictions: [
              'channel_mshops',
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          exchange_rate_context: 'DEFAULT',
          metadata: {
          },
        },
      ],
      presentation: {
        display_currency: 'BRL',
      },
      payment_method_prices: [
        {
          id: 'af83f81b-375e-45d7-8bd7-09769f983fd5',
          conditions: {
            allowed_methods: [
              {
                id: 'pix',
                issuer_id: null,
                payment_type_id: 'bank_transfer',
                installments: null,
              },
            ],
            start_time: '2022-02-11T03:00:00Z',
            end_time: '2022-02-14T02:00:00Z',
            restricted_to_prices: [
            ],
          },
          value: 5,
          type: 'percentage',
          currency_id: null,
          metadata: {
            purchase_discount_id: 'MLB580001',
            purchase_discount_type: 'BD',
            purchase_discount_campaign_id: 'P-MLB4379001',
            purchase_discount_rebate_id: 'MLB1903752342-09879416-aec1-46b9-aec4-4eb7cde93ff5',
          },
          exchange_rate_context: 'DEFAULT',
        },
        {
          id: 'c5a741f3-162d-4607-9ef0-8fec2c5f6fdb',
          conditions: {
            allowed_methods: [
              {
                id: 'pix',
                issuer_id: null,
                payment_type_id: 'bank_transfer',
                installments: null,
              },
            ],
            start_time: '2022-02-09T03:00:00Z',
            end_time: '2022-02-11T02:00:00Z',
            restricted_to_prices: [
            ],
          },
          value: 5,
          type: 'percentage',
          currency_id: null,
          metadata: {
            purchase_discount_id: 'MLB546003',
            purchase_discount_type: 'BD',
            purchase_discount_campaign_id: 'P-MLB4340001',
            purchase_discount_rebate_id: 'MLB1903752342-eea30cf1-17e4-41f7-bfee-b7827070f08a',
          },
          exchange_rate_context: 'DEFAULT',
        },
      ],
      reference_prices: [
        {
          id: '164',
          type: 'min_standard',
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          amount: 2479,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          tags: [
          ],
          last_updated: '2022-03-23T04:23:08Z',
        },
        {
          id: '165',
          type: 'was',
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: '2022-03-23T04:23:08Z',
            end_time: '2022-03-30T04:23:08Z',
            eligible: true,
          },
          amount: 2479,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          tags: [
          ],
          last_updated: '2022-03-23T04:23:08Z',
        },
      ],
      purchase_discounts: [
        {
          purchase_discount_id: 'MLB580001',
          campaign_id: 'P-MLB4379001',
          rebate_id: 'MLB1903752342-09879416-aec1-46b9-aec4-4eb7cde93ff5',
          type: 'BD',
          discount_percentage: 0.05,
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: '2022-02-11T03:00:00Z',
            end_time: '2022-02-14T02:00:00Z',
            eligible: true,
          },
          purchase_min_amount: 0,
          max_discount_amount: 120000,
          max_benefit_count: 1,
          funding_mode: 'coupon',
        },
        {
          purchase_discount_id: 'MLB546003',
          campaign_id: 'P-MLB4340001',
          rebate_id: 'MLB1903752342-eea30cf1-17e4-41f7-bfee-b7827070f08a',
          type: 'BD',
          discount_percentage: 0.05,
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: '2022-02-09T03:00:00Z',
            end_time: '2022-02-11T02:00:00Z',
            eligible: true,
          },
          purchase_min_amount: 0,
          max_discount_amount: 150000,
          max_benefit_count: 1,
          funding_mode: 'coupon',
        },
      ],
    },
    sale_price: null,
    currency_id: 'BRL',
    available_quantity: 50,
    sold_quantity: 500,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_pro',
    stop_time: '2041-11-28T13:56:09.000Z',
    condition: 'new',
    permalink: 'https://produto.mercadolivre.com.br/MLB-1903752342-geladeira-portatil-para-caminho-31-litros-resfriar-1224v-_JM',
    thumbnail: 'http://http2.mlstatic.com/D_927136-MLB49178555547_022022-I.jpg',
    thumbnail_id: '927136-MLB49178555547_022022',
    accepts_mercadopago: true,
    installments: {
      quantity: 12,
      amount: 208.25,
      rate: 0,
      currency_id: 'BRL',
    },
    address: {
      state_id: 'BR-SC',
      state_name: 'Santa Catarina',
      city_id: 'TUxCQ0NPTmI1ZDM4',
      city_name: 'Concórdia',
    },
    shipping: {
      free_shipping: true,
      mode: 'me2',
      tags: [
        'mandatory_free_shipping',
      ],
      logistic_type: 'xd_drop_off',
      store_pick_up: false,
    },
    seller_address: {
      id: '',
      comment: '',
      address_line: '',
      zip_code: '',
      country: {
        id: 'BR',
        name: 'Brasil',
      },
      state: {
        id: 'BR-SC',
        name: 'Santa Catarina',
      },
      city: {
        id: 'TUxCQ0NPTmI1ZDM4',
        name: 'Concórdia',
      },
      latitude: '',
      longitude: '',
    },
    attributes: [
      {
        name: 'Marca',
        values: [
          {
            struct: null,
            source: 3045741222775799,
            id: null,
            name: 'Resfri Ar',
          },
        ],
        id: 'BRAND',
        value_id: null,
        value_name: 'Resfri Ar',
        value_struct: null,
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        source: 3045741222775799,
      },
      {
        name: 'Condição do item',
        value_struct: null,
        values: [
          {
            id: '2230284',
            name: 'Novo',
            struct: null,
            source: 3045741222775799,
          },
        ],
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        source: 3045741222775799,
        id: 'ITEM_CONDITION',
        value_name: 'Novo',
        value_id: '2230284',
      },
    ],
    differential_pricing: {
      id: 35713368,
    },
    original_price: null,
    category_id: 'MLB60667',
    official_store_id: null,
    domain_id: 'MLB-LIGHT_VEHICLE_PARTS',
    catalog_product_id: null,
    tags: [
      'good_quality_picture',
      'good_quality_thumbnail',
      'standard_price_by_channel',
      'immediate_payment',
      'cart_eligible',
      'best_seller_candidate',
      'shipping_guaranteed',
    ],
    order_backend: 3,
    use_thumbnail_id: true,
    offer_score: null,
    offer_share: null,
    match_score: null,
    winner_item_id: null,
    melicoin: null,
    discounts: null,
  },
  {
    id: 'MLB1816997279',
    site_id: 'MLB',
    title: 'Compressor De Ar Mini A Bateria Portátil Tech One Mini Compressor De Ar Automotivo Preto',
    seller: {
      id: 196540294,
      permalink: 'http://perfil.mercadolivre.com.br/AUTOEQUIPBRASIL',
      registration_date: '2015-11-04T08:47:20.000-04:00',
      car_dealer: false,
      real_estate_agency: false,
      tags: [
        'brand',
        'large_seller',
        'eshop',
        'mshops',
        'credits_profile',
        'messages_as_seller',
      ],
      eshop: {
        seller: 196540294,
        eshop_rubro: null,
        eshop_id: 228264,
        nick_name: 'AUTOEQUIPBRASIL',
        site_id: 'MLB',
        eshop_logo_url: 'http://resources.mlstatic.com/eshops/196540294va019cb.png',
        eshop_status_id: 2,
        eshop_experience: 0,
        eshop_locations: [
        ],
      },
      seller_reputation: {
        power_seller_status: 'platinum',
        level_id: '5_green',
        metrics: {
          cancellations: {
            period: '60 days',
            rate: 0.0025,
            value: 173,
          },
          claims: {
            period: '60 days',
            rate: 0.0086,
            value: 576,
          },
          delayed_handling_time: {
            period: '60 days',
            rate: 0.0056,
            value: 367,
          },
          sales: {
            period: '60 days',
            completed: 62302,
          },
        },
        transactions: {
          canceled: 37930,
          period: 'historic',
          total: 551489,
          ratings: {
            negative: 0.04,
            neutral: 0.02,
            positive: 0.94,
          },
          completed: 513559,
        },
      },
    },
    price: 79,
    prices: {
      id: 'MLB1816997279',
      prices: [
        {
          id: '375',
          type: 'standard',
          amount: 79,
          regular_amount: null,
          currency_id: 'BRL',
          last_updated: '2022-03-21T13:22:56Z',
          conditions: {
            context_restrictions: [
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          exchange_rate_context: 'DEFAULT',
          metadata: {
          },
        },
        {
          id: '387',
          type: 'promotion',
          amount: 79,
          regular_amount: 89,
          currency_id: 'BRL',
          last_updated: '2022-04-01T12:42:45Z',
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: '2022-04-01T02:31:00Z',
            end_time: '2022-05-01T02:59:00Z',
            eligible: true,
          },
          exchange_rate_context: 'DEFAULT',
          metadata: {
            campaign_id: 'MLB8281',
            promotion_id: 'MLB8281',
            promotion_type: 'campaign',
          },
        },
        {
          id: '388',
          type: 'promotion',
          amount: 79,
          regular_amount: 89,
          currency_id: 'BRL',
          last_updated: '2022-04-01T12:42:45Z',
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: '2022-04-01T02:30:00Z',
            end_time: '2022-05-01T02:59:00Z',
            eligible: true,
          },
          exchange_rate_context: 'DEFAULT',
          metadata: {
            campaign_id: 'MLB8212',
            promotion_id: 'MLB8212',
            promotion_type: 'campaign',
          },
        },
      ],
      presentation: {
        display_currency: 'BRL',
      },
      payment_method_prices: [
      ],
      reference_prices: [
        {
          id: '380',
          type: 'min_standard',
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          amount: 65.9,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          tags: [
          ],
          last_updated: '2022-04-01T04:31:50Z',
        },
        {
          id: '381',
          type: 'was',
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: '2022-04-01T04:31:50Z',
            end_time: '2022-04-08T04:31:50Z',
            eligible: true,
          },
          amount: 65.9,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          tags: [
          ],
          last_updated: '2022-04-01T04:31:50Z',
        },
      ],
      purchase_discounts: [
      ],
    },
    sale_price: null,
    currency_id: 'BRL',
    available_quantity: 373,
    sold_quantity: 2415,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_pro',
    stop_time: '2041-12-11T12:38:06.000Z',
    condition: 'new',
    permalink: 'https://www.mercadolivre.com.br/compressor-de-ar-mini-a-bateria-portatil-tech-one-mini-compressor-de-ar-automotivo-preto/p/MLB15809946',
    thumbnail: 'http://http2.mlstatic.com/D_793173-MLA45073316929_032021-I.jpg',
    thumbnail_id: '793173-MLA45073316929_032021',
    accepts_mercadopago: true,
    installments: {
      quantity: 6,
      amount: 13.17,
      rate: 0,
      currency_id: 'BRL',
    },
    address: {
      state_id: 'BR-SP',
      state_name: 'São Paulo',
      city_id: 'BR-SP-62',
      city_name: 'Itu',
    },
    shipping: {
      free_shipping: true,
      mode: 'me2',
      tags: [
        'fulfillment',
        'mandatory_free_shipping',
      ],
      logistic_type: 'fulfillment',
      store_pick_up: false,
    },
    seller_address: {
      id: '',
      comment: '',
      address_line: '',
      zip_code: '',
      country: {
        id: 'BR',
        name: 'Brasil',
      },
      state: {
        id: 'BR-SP',
        name: 'São Paulo',
      },
      city: {
        id: 'BR-SP-62',
        name: 'Itu',
      },
      latitude: '',
      longitude: '',
    },
    attributes: [
      {
        values: [
          {
            source: 4709228965570453,
            id: '7175737',
            name: '17 cm',
            struct: {
              number: 17,
              unit: 'cm',
            },
          },
        ],
        source: 4709228965570453,
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        id: 'AIR_COMPRESSOR_LENGTH',
        name: 'Comprimento do compressor de ar',
        value_id: '7175737',
        value_name: '17 cm',
        value_struct: {
          number: 17,
          unit: 'cm',
        },
      },
      {
        value_id: '7552958',
        source: 4709228965570453,
        attribute_group_name: 'Outros',
        id: 'AIR_COMPRESSOR_WEIGHT',
        name: 'Peso do compressor de ar',
        value_name: '0.45 kg',
        value_struct: {
          number: 0.45,
          unit: 'kg',
        },
        values: [
          {
            source: 4709228965570453,
            id: '7552958',
            name: '0.45 kg',
            struct: {
              number: 0.45,
              unit: 'kg',
            },
          },
        ],
        attribute_group_id: 'OTHERS',
      },
      {
        values: [
          {
            struct: null,
            source: 1,
            id: '2786265',
            name: 'Tech One',
          },
        ],
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        id: 'BRAND',
        name: 'Marca',
        value_struct: null,
        value_id: '2786265',
        value_name: 'Tech One',
        source: 1,
      },
      {
        value_id: '8721222',
        value_name: '45 cm',
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        source: 4709228965570453,
        id: 'HOSE_LENGTH',
        name: 'Comprimento da mangueira',
        value_struct: {
          number: 45,
          unit: 'cm',
        },
        values: [
          {
            id: '8721222',
            name: '45 cm',
            struct: {
              unit: 'cm',
              number: 45,
            },
            source: 4709228965570453,
          },
        ],
      },
      {
        name: 'Inclui cilindros',
        value_id: '242085',
        value_name: 'Sim',
        value_struct: null,
        values: [
          {
            id: '242085',
            name: 'Sim',
            struct: null,
            source: 4709228965570453,
          },
        ],
        id: 'INCLUDES_CYLINDERS',
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        source: 4709228965570453,
      },
      {
        value_id: '2230284',
        value_struct: null,
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        id: 'ITEM_CONDITION',
        name: 'Condição do item',
        value_name: 'Novo',
        values: [
          {
            id: '2230284',
            name: 'Novo',
            struct: null,
            source: 1,
          },
        ],
        source: 1,
      },
      {
        values: [
          {
            id: '11428468',
            name: 'Mini Compressor de Ar Automotivo',
            struct: null,
            source: 4709228965570453,
          },
        ],
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        source: 4709228965570453,
        id: 'MODEL',
        name: 'Modelo',
        value_id: '11428468',
        value_name: 'Mini Compressor de Ar Automotivo',
        value_struct: null,
      },
      {
        value_struct: {
          number: 16.5,
          unit: 'cm',
        },
        values: [
          {
            id: null,
            name: '16.5 cm',
            struct: {
              number: 16.5,
              unit: 'cm',
            },
            source: 4333789534002961,
          },
        ],
        source: 4333789534002961,
        name: 'Comprimento da embalagem',
        value_id: null,
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        id: 'PACKAGE_LENGTH',
        value_name: '16.5 cm',
      },
      {
        source: 4333789534002961,
        id: 'PACKAGE_WEIGHT',
        name: 'Peso da embalagem',
        value_struct: {
          number: 450,
          unit: 'g',
        },
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        value_id: null,
        value_name: '450 g',
        values: [
          {
            id: null,
            name: '450 g',
            struct: {
              number: 450,
              unit: 'g',
            },
            source: 4333789534002961,
          },
        ],
      },
      {
        attribute_group_id: 'OTHERS',
        source: 3376461333454861,
        values: [
          {
            id: '-1',
            name: null,
            struct: null,
            source: 3376461333454861,
          },
        ],
        attribute_group_name: 'Outros',
        id: 'POWER',
        name: 'Potência',
        value_id: '-1',
        value_name: null,
        value_struct: null,
      },
    ],
    differential_pricing: {
      id: 35713362,
    },
    original_price: 89,
    category_id: 'MLB63533',
    official_store_id: 1441,
    domain_id: 'MLB-AIR_COMPRESSORS',
    catalog_product_id: 'MLB15809946',
    tags: [
      'brand_verified',
      'good_quality_picture',
      'good_quality_thumbnail',
      'loyalty_discount_eligible',
      'immediate_payment',
      'cart_eligible',
      'best_seller_candidate',
      'shipping_guaranteed',
    ],
    catalog_listing: true,
    use_thumbnail_id: true,
    offer_score: null,
    offer_share: null,
    match_score: null,
    winner_item_id: null,
    melicoin: null,
    discounts: null,
    order_backend: 4,
  },
  {
    id: 'MLB1743111669',
    site_id: 'MLB',
    title: 'Palhetas Limpador Parabrisa Original Bosch Aerofit Silicone',
    seller: {
      id: 164208900,
      permalink: 'http://perfil.mercadolivre.com.br/CONECTA+PARTS.',
      registration_date: '2014-08-08T15:12:47.000-04:00',
      car_dealer: false,
      real_estate_agency: false,
      tags: [
        'normal',
        'mshops',
        'credits_profile',
        'messages_as_seller',
      ],
      seller_reputation: {
        power_seller_status: 'platinum',
        level_id: '5_green',
        metrics: {
          cancellations: {
            period: '60 days',
            rate: 0,
            value: 1,
          },
          claims: {
            period: '60 days',
            rate: 0.0044,
            value: 24,
          },
          delayed_handling_time: {
            period: '60 days',
            rate: 0.0146,
            value: 78,
          },
          sales: {
            period: '60 days',
            completed: 5159,
          },
        },
        transactions: {
          canceled: 840,
          period: 'historic',
          total: 16635,
          ratings: {
            negative: 0.04,
            neutral: 0.01,
            positive: 0.95,
          },
          completed: 15795,
        },
      },
    },
    price: 77.9,
    prices: {
      id: 'MLB1743111669',
      prices: [
        {
          id: '229',
          type: 'standard',
          amount: 77.9,
          regular_amount: null,
          currency_id: 'BRL',
          last_updated: '2022-03-16T10:11:18Z',
          conditions: {
            context_restrictions: [
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          exchange_rate_context: 'DEFAULT',
          metadata: {
          },
        },
      ],
      presentation: {
        display_currency: 'BRL',
      },
      payment_method_prices: [
        {
          id: '55058ece-eeff-4331-b3fe-93d3528f5fa4',
          conditions: {
            allowed_methods: [
              {
                id: 'consumer_credits',
                issuer_id: 12364,
                payment_type_id: 'digital_currency',
                installments: null,
              },
            ],
            start_time: '2022-02-21T03:00:00Z',
            end_time: '2022-02-25T02:00:00Z',
            restricted_to_prices: [
            ],
          },
          value: 10,
          type: 'percentage',
          currency_id: null,
          metadata: {
            purchase_discount_id: 'MLB587001',
            purchase_discount_type: 'BD',
            purchase_discount_campaign_id: 'P-MLB4508001',
            purchase_discount_rebate_id: 'MLB1743111669-e803619f-2d1e-49ae-91d3-49232a41c6bb',
          },
          exchange_rate_context: 'DEFAULT',
        },
      ],
      reference_prices: [
        {
          id: '233',
          type: 'min_standard',
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: null,
            end_time: null,
            eligible: true,
          },
          amount: 77.9,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          tags: [
          ],
          last_updated: '2022-03-27T04:26:59Z',
        },
        {
          id: '234',
          type: 'was',
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: '2022-03-27T04:26:59Z',
            end_time: '2022-04-03T04:26:59Z',
            eligible: true,
          },
          amount: 74.95,
          currency_id: 'BRL',
          exchange_rate_context: 'DEFAULT',
          tags: [
          ],
          last_updated: '2022-03-27T04:26:59Z',
        },
      ],
      purchase_discounts: [
        {
          purchase_discount_id: 'MLB587001',
          campaign_id: 'P-MLB4508001',
          rebate_id: 'MLB1743111669-e803619f-2d1e-49ae-91d3-49232a41c6bb',
          type: 'BD',
          discount_percentage: 0.1,
          conditions: {
            context_restrictions: [
              'channel_marketplace',
            ],
            start_time: '2022-02-21T03:00:00Z',
            end_time: '2022-02-25T02:00:00Z',
            eligible: true,
          },
          purchase_min_amount: 0,
          max_discount_amount: 70,
          max_benefit_count: 1,
          funding_mode: 'coupon',
        },
      ],
    },
    sale_price: null,
    currency_id: 'BRL',
    available_quantity: 5000,
    sold_quantity: 5000,
    buying_mode: 'buy_it_now',
    listing_type_id: 'gold_pro',
    stop_time: '2042-01-10T16:44:27.000Z',
    condition: 'new',
    permalink: 'https://produto.mercadolivre.com.br/MLB-1743111669-palhetas-limpador-parabrisa-original-bosch-aerofit-silicone-_JM',
    thumbnail: 'http://http2.mlstatic.com/D_908098-MLB48245250077_112021-I.jpg',
    thumbnail_id: '908098-MLB48245250077_112021',
    accepts_mercadopago: true,
    installments: {
      quantity: 6,
      amount: 12.98,
      rate: 0,
      currency_id: 'BRL',
    },
    address: {
      state_id: 'BR-SC',
      state_name: 'Santa Catarina',
      city_id: 'TUxCQ0JMVWM2MDMx',
      city_name: 'Blumenau',
    },
    shipping: {
      free_shipping: false,
      mode: 'me2',
      tags: [
      ],
      logistic_type: 'cross_docking',
      store_pick_up: false,
    },
    seller_address: {
      id: '',
      comment: '',
      address_line: '',
      zip_code: '',
      country: {
        id: 'BR',
        name: 'Brasil',
      },
      state: {
        id: 'BR-SC',
        name: 'Santa Catarina',
      },
      city: {
        id: 'TUxCQ0JMVWM2MDMx',
        name: 'Blumenau',
      },
      latitude: '',
      longitude: '',
    },
    attributes: [
      {
        value_id: '4946',
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        id: 'BRAND',
        name: 'Marca',
        value_name: 'Bosch',
        value_struct: null,
        values: [
          {
            id: '4946',
            name: 'Bosch',
            struct: null,
            source: 3376461333454861,
          },
        ],
        source: 3376461333454861,
      },
      {
        value_id: '2230284',
        values: [
          {
            id: '2230284',
            name: 'Novo',
            struct: null,
            source: 3045741222775799,
          },
        ],
        id: 'ITEM_CONDITION',
        name: 'Condição do item',
        value_name: 'Novo',
        value_struct: null,
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        source: 3045741222775799,
      },
      {
        id: 'MODEL',
        value_name: 'Aerofit Bosch',
        values: [
          {
            struct: null,
            source: 3376461333454861,
            id: null,
            name: 'Aerofit Bosch',
          },
        ],
        name: 'Modelo',
        value_id: null,
        value_struct: null,
        attribute_group_id: 'OTHERS',
        attribute_group_name: 'Outros',
        source: 3376461333454861,
      },
    ],
    differential_pricing: {
      id: 35713362,
    },
    original_price: null,
    category_id: 'MLB63484',
    official_store_id: null,
    domain_id: 'MLB-WINDSHIELD_WIPERS',
    catalog_product_id: null,
    tags: [
      'brand_verified',
      'good_quality_picture',
      'good_quality_thumbnail',
      'loyalty_discount_eligible',
      'immediate_payment',
      'cart_eligible',
      'best_seller_candidate',
    ],
    order_backend: 5,
    use_thumbnail_id: true,
    offer_score: null,
    offer_share: null,
    match_score: null,
    winner_item_id: null,
    melicoin: null,
    discounts: null,
  }];

export default data;
